version: 2.1

jobs:
  build-all:
    machine: true
    resource_class: e-yes/xgo2-buildroot

    steps:
      - checkout

      - run:
          name: Build Buildroot
          command: |
            pwd
            mkdir -p whatever/dir
            echo "meow"
            date > whatever/dir/tmp.txt

workflows:
  version: 2
  build:
    jobs:
      - build-all:
          filters:
            branches:
              only:
                - master
                - /releases\/v.*/
                - develop
                - br
